Vidsrc devices list (#491)
* Add device_list to videosrc:
- set_available_devices implementation in v4l2 module
- check video source devices availability in switch_video_source

* Fix compilation error: bad line break in printf message

* Fix coding style

* - mediadev: data structure and related functions moved in mediadev.c
- vidsrc switching: no device availability check if the module does not support mediadev

* Revert avformat unwanted commit...

* mediadev: mediadev_get_default helper function and minor fixes

* mediadev: fix compilation error/warning

* mediadev: try to set relevant default video source device in default config template

* mediadev:
- fix mediadev_get_default error handling
- implementation in default config template suppressed