Fix win32 (#1579)
* win32: fix error C7555: use of designated initializers requires at least '/std:c++latest'
 (after commit to rem: 11a1bcfffda095d3187662809fdeacedb9ec72a3)

* win32. fix project source files filter  (follows after e831d684d50fb9b7b28750a8dbc62624f21b2e66 )

* win32: remove sources from project (follows after rem commits
8feb18c095c42f82066629b247b8e31c06a0eb98
5307c3415c9ef19381784c67fa610e42d143b9d3
0bda27ab1fb4d5187761899edaf2b0944451fc7f )

* win32: include sources to project (follows after 92fee52809b6661d5c3a4bbf48f5f140c974e694 )

* turn: fix compile for non TLS (follows after d5d9ab8d5f4e526e550bed446c6cbca0a78b976d )

* fix ccheck (./modules/turn/turn.c:284: has trailing space(s))